command_timeout=1000

format = """\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $hg_branch\
    $dotnet\
    $golang\
    $java\
    $nodejs\
    $php\
    $python\
    $ruby\
    $rust\
    $terraform\
    $nix_shell\
    $conda\
    $memory_usage\
    $aws\
    $env_var\
    $cmd_duration\
    $line_break\
    $jobs\
    $battery\
    $time\
    $character
"""

[character]
success_symbol = "➜"
error_symbol = "✗"

[git_branch]
symbol = "🌱 "
truncation_length = 15
truncation_symbol = "➜"

[aws]
style = "bold blue"
symbol = "🅰 "
